### ISSUE TITLE
Support verbose/granular output levels

### ISSUE THREAD

**Issue by alicerum** [shipwright-io/cli#7]
As discussed in #6 , `cli` should output via `klog` and support multiple levels of verbosity.

**Comment by adambkaplan** [comment]
/kind feature

Marking this a feature since we would expose a `-v` option for log verbosity.

**Comment by coreydaley** [comment]
I think that we already went through the whole klog thing: https://github.com/shipwright-io/cli/pull/13

**Comment by jerolimov** [comment]
Oh thanks for that PR @coreydaley. Sorry I didn't know that on the hackday on Friday, otherwise I had picked up your earlier work. As posted in #71 you can see that my PR only initialize `klog`. I don't updated any output of `shp` itself. So the current output should be the same. It only allows users to enable additional logging. Only if an user do that she/he will see that that timestamps. From my understand that was the reason you and @adambkaplan decided in #13 to skip that for that moment, right?
